#spring:
#  application:
#    name: CommonIntegration
#
#
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://localhost:8083/eureka/
#server:
#  port: 8091
#xiayu:
#  feature:
#    mail: true
