spring:
  application:
    name: configcenter
  cloud:
    config:
      server:
        git:
          uri: https://github.com/yougoodigood/xiayuapplication
          search-paths: /config
      label: master

server:
  port: 8087