spring:
  application:
    name: PublicGateWay
server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8083/eureka/
zuul:
  routes:
    api-user:
      path: /api-user/**
      serviceId: UserService
    api-order:
      path: /api-order/**
      serviceId: CommonIntegration
  strip-prefix: false