spring:
  application:
    name: UserService
  rabbitmq:
    password: guest
    username: guest
    host: localhost
    port: 5672
  cloud:
    bus:
      enabled: true
      trace:
        enabled: true
server:
  port: 8085
feign:
  hystrix:
    enabled: true
management:
  endpoints:
    web:
      exposure:
        include: bus-refresh