spring:
  application:
    name: EurekaRigstryCenterApplication
server:
  port: 8082

eureka:
  instance:
    hostname: localhost
  client:
#    registerWithEureka: false
#    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8083/eureka/
